a31

diff --git a/.github/workflows/build-and-release.yaml b/.github/workflows/build-and-release.yaml
--- a/.github/workflows/build-and-release.yaml
+++ b/.github/workflows/build-and-release.yaml
@@ -30,21 +30,21 @@ jobs:
                   echo "Listing jar files in build/libs:"
                   ls build/libs/*.jar
 
-                  - name: Get Release Upload URL
-                  id: get_release
-                  run: |
-                    response=$(curl -s \
-                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-                      https://api.github.com/repos/${{ github.repository }}/releases/tags/v0.5.4)
+            - name: Get Release Upload URL
+              id: get_release
+              run: |
+                  response=$(curl -s \
+                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+                    https://api.github.com/repos/${{ github.repository }}/releases/tags/v0.5.4)
 
-                    upload_url=$(echo "$response" | jq -r .upload_url | sed -e "s/{?name,label}//")
+                  upload_url=$(echo "$response" | jq -r .upload_url | sed -e "s/{?name,label}//")
 
-                    if [ -z "$upload_url" ]; then
-                      echo "Error: Failed to retrieve upload_url."
-                      exit 1
-                    fi
+                  if [ -z "$upload_url" ]; then
+                    echo "Error: Failed to retrieve upload_url."
+                    exit 1
+                  fi
 
-                    echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
+                  echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
 
             - name: Upload JAR - All JAR
               uses: actions/upload-release-asset@v1
