a

diff --git a/.github/workflows/build-and-release.yaml b/.github/workflows/build-and-release.yaml
--- a/.github/workflows/build-and-release.yaml
+++ b/.github/workflows/build-and-release.yaml
@@ -38,7 +38,11 @@ jobs:
                     -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     https://api.github.com/repos/${{ github.repository }}/releases/tags/v0.5.4 \
                     | jq -r .upload_url | sed -e "s/{?name,label}//")
-                  echo "::set-output name=upload_url::$upload_url" || exit 1
+                  if [ -z "$upload_url" ]; then
+                    echo "Failed to get upload URL."
+                    exit 1
+                  fi
+                  echo "::set-output name=upload_url::$upload_url"
 
             - name: Upload JAR - Main
               uses: actions/upload-release-asset@v1
